"""In-memory log of executed actions, with export helpers."""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from gui4aws.execution.execution_mode import ExecutionMode

__all__ = ["ActionHistory", "ActionHistoryEntry"]


@dataclass(frozen=True)
class ActionHistoryEntry:
    """One executed action."""

    timestamp: datetime
    service_id: str
    action_id: str
    mode: ExecutionMode
    profile_name: str | None
    region_name: str
    endpoint_url: str | None
    inputs: Mapping[str, str]
    cli_script: str
    python_script: str
    status: str  # "success" | "failure"
    duration_seconds: float
    error_message: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Plain-JSON-friendly representation."""
        return {
            "timestamp": self.timestamp.isoformat(),
            "service_id": self.service_id,
            "action_id": self.action_id,
            "mode": str(self.mode),
            "profile_name": self.profile_name,
            "region_name": self.region_name,
            "endpoint_url": self.endpoint_url,
            "inputs": dict(self.inputs),
            "cli_script": self.cli_script,
            "python_script": self.python_script,
            "status": self.status,
            "duration_seconds": self.duration_seconds,
            "error_message": self.error_message,
        }


@dataclass
class ActionHistory:
    """Append-only log of executed actions."""

    max_entries: int = 500
    entries: list[ActionHistoryEntry] = field(default_factory=list)

    def add(self, entry: ActionHistoryEntry) -> None:
        """Append an entry, trimming the oldest if over max_entries."""
        self.entries.append(entry)
        if len(self.entries) > self.max_entries:
            del self.entries[: len(self.entries) - self.max_entries]

    def latest(self) -> ActionHistoryEntry | None:
        """Most recent entry, or None."""
        return self.entries[-1] if self.entries else None

    def export_bash(self, entries: Iterable[ActionHistoryEntry] | None = None) -> str:
        """Concatenate the CLI scripts for the chosen entries (or all) into one bash file."""
        chosen = list(entries) if entries is not None else self.entries
        lines = ["#!/usr/bin/env bash", "set -euo pipefail", ""]
        for entry in chosen:
            lines.append(f"# {entry.timestamp.isoformat()} {entry.action_id}")
            for raw in entry.cli_script.splitlines():
                if raw.startswith("#!"):
                    continue
                if raw.startswith("set -euo"):
                    continue
                lines.append(raw)
            lines.append("")
        return "\n".join(lines)

    def export_python(self, entries: Iterable[ActionHistoryEntry] | None = None) -> str:
        """Concatenate the Python scripts for the chosen entries into one script.

        Each entry becomes a numbered ``def step_N()`` function plus a ``main`` that calls them
        in order. This intentionally produces boring, readable Python.
        """
        chosen = list(entries) if entries is not None else self.entries
        lines = [
            '"""Generated by gui4aws action history. Safe to paste into a real project."""',
            "from __future__ import annotations",
            "",
            "import boto3",
            "",
        ]
        for index, entry in enumerate(chosen, start=1):
            lines.append(f"def step_{index}() -> None:")
            lines.append(f'    """{entry.action_id} at {entry.timestamp.isoformat()}."""')
            for raw in indent_inside_main(entry.python_script):
                lines.append(raw)
            lines.append("")

        lines.append("def main() -> None:")
        if chosen:
            for index in range(1, len(chosen) + 1):
                lines.append(f"    step_{index}()")
        else:
            lines.append("    pass")
        lines.extend(["", 'if __name__ == "__main__":', "    main()", ""])
        return "\n".join(lines)

    def export_json(self) -> str:
        """Whole history as JSON."""
        return json.dumps([entry.to_dict() for entry in self.entries], indent=2)


def indent_inside_main(python_script: str) -> list[str]:
    """Extract the body of ``def main()`` from a generated script, keeping its indentation."""
    body: list[str] = []
    in_main = False
    for raw in python_script.splitlines():
        if raw.startswith("def main()"):
            in_main = True
            continue
        if in_main:
            if raw.startswith("if __name__"):
                break
            body.append(raw)
    if not body:
        # No main block found; fall back to a pass.
        return ["    pass"]
    while body and not body[-1].strip():
        body.pop()
    return body
