"""Render ActionDefinition + inputs as standalone AWS CLI or Python scripts.

Generated scripts must be paste-into-a-real-project ready:

- No imports from gui4aws.
- No clever runtime dispatch.
- Profile, region, endpoint URL all inlined.
"""

from __future__ import annotations

from collections.abc import Mapping

from gui4aws.execution.aws_cli_executor import quote_for_shell
from gui4aws.execution.boto3_executor import coerce_value
from gui4aws.execution.endpoint_config import EndpointConfig
from gui4aws.models import ActionDefinition

__all__ = ["generate_cli_script", "generate_python_script"]


def generate_cli_script(
    action: ActionDefinition,
    inputs: Mapping[str, str],
    *,
    profile_name: str | None,
    region_name: str,
    endpoint_config: EndpointConfig,
) -> str:
    """Render the action as a bash script using the AWS CLI."""
    template = action.cli_template
    argv: list[str] = ["aws", template.service, template.command]
    argv.extend(["--region", region_name])
    if profile_name:
        argv.extend(["--profile", profile_name])
    endpoint_url = endpoint_config.resolved_url()
    if endpoint_url is not None:
        argv.extend(["--endpoint-url", endpoint_url])

    if action.cli_args_builder is not None:
        argv.extend(action.cli_args_builder(inputs))
    else:
        arg_map = template.arg_map
        for input_field in action.input_fields:
            value = inputs.get(input_field.name)
            if value is None or value == "":
                continue
            flag = arg_map.get(input_field.name)
            if flag is None:
                continue
            if input_field.kind == "bool":
                if value.strip().lower() in {"true", "yes", "1", "on"}:
                    argv.append(f"--{flag}")
                else:
                    argv.append(f"--no-{flag}")
            elif input_field.kind == "list":
                items = [item.strip() for item in value.split(",") if item.strip()]
                if items:
                    argv.append(f"--{flag}")
                    argv.extend(items)
            else:
                argv.extend([f"--{flag}", value])

    # Render as multi-line with one flag per line so no horizontal scrolling is needed.
    # "aws rds create-db-cluster-snapshot \" on line 1, then "  --flag value \" per flag.
    cmd_parts: list[str] = []
    i = 0
    while i < len(argv):
        part = argv[i]
        if part.startswith("--") and i + 1 < len(argv) and not argv[i + 1].startswith("--"):
            cmd_parts.append(f"  {quote_for_shell([part, argv[i + 1]])}")
            i += 2
        else:
            cmd_parts.append(f"  {quote_for_shell([part])}" if part.startswith("--") else quote_for_shell([part]))
            i += 1

    # First element is "aws service command" (3 tokens), rest are flags.
    base = " ".join(cmd_parts[:3])
    flag_lines = cmd_parts[3:]

    lines = ["#!/usr/bin/env bash", "set -euo pipefail", ""]
    lines.append("# " + action.display_name)
    if flag_lines:
        lines.append(base + " \\")
        for j, fl in enumerate(flag_lines):
            suffix = " \\" if j < len(flag_lines) - 1 else ""
            lines.append(fl + suffix)
    else:
        lines.append(base)
    lines.append("")
    return "\n".join(lines)


def generate_python_script(
    action: ActionDefinition,
    inputs: Mapping[str, str],
    *,
    profile_name: str | None,
    region_name: str,
    endpoint_config: EndpointConfig,
) -> str:
    """Render the action as a standalone boto3 Python script."""
    template = action.boto3_template
    if action.boto3_params_builder is not None:
        params = action.boto3_params_builder(inputs)
    else:
        params = {}
        for input_field in action.input_fields:
            value = inputs.get(input_field.name)
            if value is None or value == "":
                continue
            boto_name = template.param_map.get(input_field.name, input_field.name)
            params[boto_name] = coerce_value(value, input_field.kind)

    profile_repr = repr(profile_name) if profile_name else "None"
    region_repr = repr(region_name)
    endpoint_url = endpoint_config.resolved_url()
    endpoint_repr = repr(endpoint_url) if endpoint_url else None

    lines = [
        '"""Generated by gui4aws. Safe to paste into a real project."""',
        "from __future__ import annotations",
        "",
        "import boto3",
        "",
        "",
        "def main() -> None:",
        f"    session = boto3.Session(profile_name={profile_repr}, region_name={region_repr})",
    ]
    if endpoint_repr is not None:
        lines.append(f'    client = session.client("{template.service}", endpoint_url={endpoint_repr})')
    else:
        lines.append(f'    client = session.client("{template.service}")')

    if params:
        lines.append(f"    response = client.{template.operation}(")
        for key, val in params.items():
            lines.append(f"        {key}={val!r},")
        lines.append("    )")
    else:
        lines.append(f"    response = client.{template.operation}()")
    lines.extend(
        [
            "    print(response)",
            "",
            "",
            'if __name__ == "__main__":',
            "    main()",
            "",
        ]
    )
    return "\n".join(lines)
